// import "core-js/stable";
import "regenerator-runtime/runtime";
import "./debug";

export { roDispatchAction, roDispatchFunction, roPushHistory } from "./actions";
export { logger } from "./app";
export { createActionHandlerDecorator } from "./decorator";
export { additionLoading, interval, loading, mutex, pageLoading, retryOnNetworkConnectionError } from "./decorator/module";
export { APIException, Exception, NetworkConnectionException } from "./Exception";
export { useAction, useBinaryAction, useLoading, useObjectKeyAction, useUnaryAction } from "./hooks";
export type { ErrorListener } from "./module";
export { register } from "./module";
export { bootstrap } from "./platform/bootstrap";
export { Module } from "./platform/Module";
export { ModuleNameContext } from "./platform/ModuleProxy";
export type { Action, State } from "./reducer";
export { loadingAction, navigationPreventionAction, pageLoadingAction, showLoading } from "./reducer";
export type { AsyncErrorComponentProps, AsyncOptions, ReactComponentKeyOf } from "./util/async";
export { async } from "./util/async";
export { captureError } from "./util/error-util";
export { ErrorBoundary } from "./util/ErrorBoundary";
export { Route } from "./util/Route";
