import TitleConfig from "./titleConfig";

export enum EchartsNodeType {
    null = "null",
    string = "string",
    number = "number",
    boolean = "boolean",
    function = "function",
    options = "options",
}

export interface EchartsTreeState {
    id: string;
    name: string;
    nodeType: EchartsNodeType | keyof typeof EchartsNodeType;
    isLeaf: boolean;
    level: number;

    sort?: number;
    options?: "";
    value?: "";
    defaultValue?: "";
    descendant?: EchartsTreeState[];
    description?: string;
}

const echartsTreeState: EchartsTreeState[] = [
    {
        sort: 0,
        id: "title",
        name: "title",
        nodeType: "null",
        isLeaf: false,
        level: 1,
        descendant: TitleConfig,
    },
    {
        sort: 2,
        id: "legend",
        name: "legend",
        nodeType: "null",
        isLeaf: false,
        level: 1,
        descendant: [],
    },
    {
        sort: 3,
        id: "grid",
        name: "grid",
        nodeType: "null",
        isLeaf: false,
        level: 1,
        descendant: [],
    },
    {
        sort: 4,
        id: "xAxis",
        name: "xAxis",
        nodeType: "null",
        isLeaf: false,
        level: 1,
        descendant: [],
    },
    {
        sort: 5,
        id: "yAxis",
        name: "yAxis",
        nodeType: "null",
        isLeaf: false,
        level: 1,
        descendant: [],
    },
    // {
    //     sort: 6,
    //     id: "polar",
    //     name: "polar",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 7,
    //     id: "radiusAxis",
    //     name: "radiusAxis",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 8,
    //     id: "angleAxis",
    //     name: "angleAxis",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 9,
    //     id: "radar",
    //     name: "radar",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 10,
    //     id: "dataZoom",
    //     name: "dataZoom",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 11,
    //     id: "visualMap",
    //     name: "visualMap",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 12,
    //     id: "tooltip",
    //     name: "tooltip",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 13,
    //     id: "axisPointer",
    //     name: "axisPointer",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 14,
    //     id: "toolbox",
    //     name: "toolbox",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 15,
    //     id: "brush",
    //     name: "brush",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 16,
    //     id: "geo",
    //     name: "geo",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 17,
    //     id: "parallel",
    //     name: "parallel",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 18,
    //     id: "parallelAxis",
    //     name: "parallelAxis",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 19,
    //     id: "singleAxis",
    //     name: "singleAxis",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 20,
    //     id: "timeline",
    //     name: "timeline",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 21,
    //     id: "graphic",
    //     name: "graphic",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 22,
    //     id: "calendar",
    //     name: "calendar",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 23,
    //     id: "matrix",
    //     name: "matrix",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 24,
    //     id: "dataset",
    //     name: "dataset",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 25,
    //     id: "aria",
    //     name: "aria",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 26,
    //     id: "series",
    //     name: "series",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 27,
    //     id: "darkMode",
    //     name: "darkMode",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 28,
    //     id: "color",
    //     name: "color",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 29,
    //     id: "backgroundColor",
    //     name: "backgroundColor",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 30,
    //     id: "textStyle",
    //     name: "textStyle",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 31,
    //     id: "animation",
    //     name: "animation",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 32,
    //     id: "animationThreshold",
    //     name: "animationThreshold",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 33,
    //     id: "animationDuration",
    //     name: "animationDuration",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 34,
    //     id: "animationEasing",
    //     name: "animationEasing",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 35,
    //     id: "animationDelay",
    //     name: "animationDelay",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 36,
    //     id: "animationDurationUpdate",
    //     name: "animationDurationUpdate",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 37,
    //     id: "animationEasingUpdate",
    //     name: "animationEasingUpdate",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 38,
    //     id: "animationDelayUpdate",
    //     name: "animationDelayUpdate",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 39,
    //     id: "stateAnimation",
    //     name: "stateAnimation",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 40,
    //     id: "blendMode",
    //     name: "blendMode",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 41,
    //     id: "hoverLayerThreshold",
    //     name: "hoverLayerThreshold",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 42,
    //     id: "useUTC",
    //     name: "useUTC",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 43,
    //     id: "richInheritPlainLabel",
    //     name: "richInheritPlainLabel",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 44,
    //     id: "options",
    //     name: "options",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
    // {
    //     sort: 45,
    //     id: "media",
    //     name: "media",
    //     nodeType: "null",
    //     isLeaf: false,
    //     level: 1,
    //     descendant: [],
    // },
];

export default echartsTreeState;
