import { EchartsTreeState } from "./config";

const legendConfig: EchartsTreeState[] = [
    {
        sort: 0,
        level: 2,
        parentPath: ["legend"],
        id: "type",
        name: "type",
        description: "图例的类型。可选值：",
        options: [
            {
                des: "'plain'",
            },
            {
                des: "'scroll'",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 1,
        level: 2,
        parentPath: ["legend"],
        id: "id",
        name: "id",
        description: "组件 ID。默认不指定。指定则可用于在 option 或者 API 中引用组件。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 2,
        level: 2,
        parentPath: ["legend"],
        id: "show",
        name: "show",
        options: [],
        propTypes: ["boolean"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 3,
        level: 2,
        parentPath: ["legend"],
        id: "zlevel",
        name: "zlevel",
        description: "所有图形的 zlevel 值。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 4,
        level: 2,
        parentPath: ["legend"],
        id: "z",
        name: "z",
        description: "组件的所有图形的z值。控制图形的前后顺序。z值小的图形会被z值大的图形覆盖。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 5,
        level: 2,
        parentPath: ["legend"],
        id: "left",
        name: "left",
        description: "undefined组件离容器左侧的距离。",
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 6,
        level: 2,
        parentPath: ["legend"],
        id: "top",
        name: "top",
        description: "undefined组件离容器上侧的距离。",
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 7,
        level: 2,
        parentPath: ["legend"],
        id: "right",
        name: "right",
        description: "undefined组件离容器右侧的距离。",
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 8,
        level: 2,
        parentPath: ["legend"],
        id: "bottom",
        name: "bottom",
        description: "undefined组件离容器下侧的距离。",
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 9,
        level: 2,
        parentPath: ["legend"],
        id: "width",
        name: "width",
        description: "图例（legend）组件的宽度。默认自适应。",
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 10,
        level: 2,
        parentPath: ["legend"],
        id: "height",
        name: "height",
        description: "图例（legend）组件的高度。默认自适应。",
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 11,
        level: 2,
        parentPath: ["legend"],
        id: "coordinateSystem",
        name: "coordinateSystem",
        description: "指定另一个坐标系组件，本 legend 布局在那个坐标系中。",
        options: [
            {
                key: "null、undefined 或者 'none'",
                des: "null",
            },
            {
                key: "'calendar'",
                des: "'calendar'",
            },
            {
                key: "'matrix'",
                des: "'matrix'",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 12,
        level: 2,
        parentPath: ["legend"],
        id: "coordinateSystemUsage",
        name: "coordinateSystemUsage",
        description: "如何在指定的 坐标系 上布局本 legend。",
        options: [
            {
                key: "'data'：（不适用于 legend）",
                des: "'data'",
            },
            {
                key: "'box'：",
                des: "'box'",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 13,
        level: 2,
        parentPath: ["legend"],
        id: "coord",
        name: "coord",
        description: "当 coordinateSystemUsage 为 'box' 时, coord 被输入给坐标系，计算得到布局位置（布局盒或者中心点）。",
        options: [],
        propTypes: ["array", "string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 14,
        level: 2,
        parentPath: ["legend"],
        id: "calendarIndex",
        name: "calendarIndex",
        description: "布局时所基于的 日历坐标系 的 index。当一个 ECharts 实例中存在多个日历坐标系时，用其指定所使用的坐标系。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 15,
        level: 2,
        parentPath: ["legend"],
        id: "calendarId",
        name: "calendarId",
        description: "布局时所基于的 日历坐标系 的 id。当一个 ECharts 实例中存在多个日历坐标系时，用其指定所使用的坐标系。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 16,
        level: 2,
        parentPath: ["legend"],
        id: "matrixIndex",
        name: "matrixIndex",
        description: "布局时所基于的 矩阵坐标系 的 index。当一个 ECharts 实例中存在多个矩阵坐标系时，用其指定所使用的坐标系。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 17,
        level: 2,
        parentPath: ["legend"],
        id: "matrixId",
        name: "matrixId",
        description: "布局时所基于的 矩阵坐标系 的 id。当一个 ECharts 实例中存在多个矩阵坐标系时，用其指定所使用的坐标系。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 18,
        level: 2,
        parentPath: ["legend"],
        id: "orient",
        name: "orient",
        description: "图例列表的布局朝向。",
        options: [
            {
                des: "'horizontal'",
            },
            {
                des: "'vertical'",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 19,
        level: 2,
        parentPath: ["legend"],
        id: "align",
        name: "align",
        description:
            "图例标记和文本的对齐。默认自动，根据组件的位置和 orient 决定，当组件的 left 值为 'right' 以及纵向布局（orient 为 'vertical'）的时候为右对齐，即为 'right'。",
        options: [
            {
                des: "'auto'",
            },
            {
                des: "'left'",
            },
            {
                des: "'right'",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 20,
        level: 2,
        parentPath: ["legend"],
        id: "padding",
        name: "padding",
        description: "图例内边距，单位px，默认各方向内边距为5，接受数组分别设定上右下左边距。",
        options: [],
        propTypes: ["number", "array"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 21,
        level: 2,
        parentPath: ["legend"],
        id: "itemGap",
        name: "itemGap",
        description: "图例每项之间的间隔。横向布局时为水平间隔，纵向布局时为纵向间隔。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 22,
        level: 2,
        parentPath: ["legend"],
        id: "itemWidth",
        name: "itemWidth",
        description: "图例标记的图形宽度。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 23,
        level: 2,
        parentPath: ["legend"],
        id: "itemHeight",
        name: "itemHeight",
        description: "图例标记的图形高度。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 24,
        level: 2,
        parentPath: ["legend"],
        id: "itemStyle",
        name: "itemStyle",
        description: "图例的图形样式。其属性的取值为 'inherit' 时，表示继承系列中的属性值。",
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "color",
                name: "color",
                description: "图形的颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 1,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "borderColor",
                name: "borderColor",
                description: "图形的描边颜色。支持的颜色格式同 color，不支持回调函数。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 2,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "borderWidth",
                name: "borderWidth",
                description:
                    '当其值为 "auto" 时，如果系列有 borderWidth 取 2，如果系列没有 borderWidth 则取 0。当其值为 "inherit" 时，始终取系列的 borderWidth。',
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 3,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "borderType",
                name: "borderType",
                description: "描边类型。",
                options: [
                    {
                        des: "'solid'",
                    },
                    {
                        des: "'dashed'",
                    },
                    {
                        des: "'dotted'",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 4,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "borderDashOffset",
                name: "borderDashOffset",
                description: "用于设置虚线的偏移量，可搭配 borderType 指定 dash array 实现灵活的虚线效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 5,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "borderCap",
                name: "borderCap",
                description: "用于指定线段末端的绘制方式，可以是：",
                options: [
                    {
                        des: "'butt'",
                    },
                    {
                        des: "'round'",
                    },
                    {
                        des: "'square'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 6,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "borderJoin",
                name: "borderJoin",
                description:
                    "用于设置2个长度不为0的相连部分（线段，圆弧，曲线）如何连接在一起的属性（长度为0的变形部分，其指定的末端和控制点在同一位置，会被忽略）。",
                options: [
                    {
                        des: "'bevel'",
                    },
                    {
                        des: "'round'",
                    },
                    {
                        des: "'miter'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 7,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "borderMiterLimit",
                name: "borderMiterLimit",
                description: "用于设置斜接面限制比例。只有当 borderJoin 为 miter 时， borderMiterLimit 才有效。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 8,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "shadowBlur",
                name: "shadowBlur",
                description: "图形阴影的模糊大小。该属性配合 shadowColor,shadowOffsetX, shadowOffsetY 一起设置图形的阴影效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 9,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "shadowColor",
                name: "shadowColor",
                description: "阴影颜色。支持的格式同color。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 10,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "shadowOffsetX",
                name: "shadowOffsetX",
                description: "阴影水平方向上的偏移距离。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 11,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "shadowOffsetY",
                name: "shadowOffsetY",
                description: "阴影垂直方向上的偏移距离。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 12,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "opacity",
                name: "opacity",
                description: "图形透明度。支持从 0 到 1 的数字，为 0 时不绘制该图形。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 13,
                level: 3,
                parentPath: ["legend", "itemStyle"],
                id: "decal",
                name: "decal",
                description: "图形的贴花图案，在 aria.enabled 与 aria.decal.show 都是 true 的情况下才生效。",
                options: [],
                propTypes: ["object"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 25,
        level: 2,
        parentPath: ["legend"],
        id: "lineStyle",
        name: "lineStyle",
        description: "图例图形中线的样式，用于诸如折线图图例横线的样式设置。其属性的取值为 'inherit' 时，表示继承系列中的属性值。",
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "color",
                name: "color",
                description: "线的颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 1,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "width",
                name: "width",
                description: "线宽。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 2,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "type",
                name: "type",
                description: "线的类型。",
                options: [
                    {
                        des: "'solid'",
                    },
                    {
                        des: "'dashed'",
                    },
                    {
                        des: "'dotted'",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 3,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "dashOffset",
                name: "dashOffset",
                description: "用于设置虚线的偏移量，可搭配 type 指定 dash array 实现灵活的虚线效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 4,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "cap",
                name: "cap",
                description: "用于指定线段末端的绘制方式，可以是：",
                options: [
                    {
                        des: "'butt'",
                    },
                    {
                        des: "'round'",
                    },
                    {
                        des: "'square'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 5,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "join",
                name: "join",
                description:
                    "用于设置2个长度不为0的相连部分（线段，圆弧，曲线）如何连接在一起的属性（长度为0的变形部分，其指定的末端和控制点在同一位置，会被忽略）。",
                options: [
                    {
                        des: "'bevel'",
                    },
                    {
                        des: "'round'",
                    },
                    {
                        des: "'miter'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 6,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "miterLimit",
                name: "miterLimit",
                description: "用于设置斜接面限制比例。只有当 join 为 miter 时， miterLimit 才有效。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 7,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "shadowBlur",
                name: "shadowBlur",
                description: "图形阴影的模糊大小。该属性配合 shadowColor,shadowOffsetX, shadowOffsetY 一起设置图形的阴影效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 8,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "shadowColor",
                name: "shadowColor",
                description: "阴影颜色。支持的格式同color。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 9,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "shadowOffsetX",
                name: "shadowOffsetX",
                description: "阴影水平方向上的偏移距离。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 10,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "shadowOffsetY",
                name: "shadowOffsetY",
                description: "阴影垂直方向上的偏移距离。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 11,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "opacity",
                name: "opacity",
                description: "图形透明度。支持从 0 到 1 的数字，为 0 时不绘制该图形。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 12,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "inactiveColor",
                name: "inactiveColor",
                description: "图例关闭时的线条描边颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 13,
                level: 3,
                parentPath: ["legend", "lineStyle"],
                id: "inactiveWidth",
                name: "inactiveWidth",
                description: "图例关闭时的线条宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 26,
        level: 2,
        parentPath: ["legend"],
        id: "symbolRotate",
        name: "symbolRotate",
        description: "图形旋转角度，类型为 number | 'inherit'。如果为 'inherit'，表示取系列的 symbolRotate。",
        options: [],
        propTypes: ["number", "string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 27,
        level: 2,
        parentPath: ["legend"],
        id: "formatter",
        name: "formatter",
        description: "用来格式化图例文本，支持字符串模板和回调函数两种形式。",
        options: [],
        propTypes: ["string", "function"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 28,
        level: 2,
        parentPath: ["legend"],
        id: "selectedMode",
        name: "selectedMode",
        description: "图例选择的模式，控制是否可以通过点击图例改变系列的显示状态。默认开启图例选择，可以设成 false 关闭。",
        options: [],
        propTypes: ["string", "boolean"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 29,
        level: 2,
        parentPath: ["legend"],
        id: "inactiveColor",
        name: "inactiveColor",
        description: "图例关闭时的颜色。",
        options: [],
        propTypes: ["color"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 30,
        level: 2,
        parentPath: ["legend"],
        id: "inactiveBorderColor",
        name: "inactiveBorderColor",
        description: "图例关闭时的描边颜色。",
        options: [],
        propTypes: ["color"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 31,
        level: 2,
        parentPath: ["legend"],
        id: "inactiveBorderWidth",
        name: "inactiveBorderWidth",
        description: "图例关闭时的描边粗细。",
        options: [],
        propTypes: ["number", "string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 32,
        level: 2,
        parentPath: ["legend"],
        id: "selected",
        name: "selected",
        description: "图例选中状态表。",
        options: [],
        propTypes: ["object"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 33,
        level: 2,
        parentPath: ["legend"],
        id: "textStyle",
        name: "textStyle",
        description: "图例的公用文本样式。",
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "color",
                name: "color",
                description: "文字的颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 1,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "fontStyle",
                name: "fontStyle",
                description: "文字字体的风格。",
                options: [
                    {
                        des: "'normal'",
                    },
                    {
                        des: "'italic'",
                    },
                    {
                        des: "'oblique'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 2,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "fontWeight",
                name: "fontWeight",
                description: "文字字体的粗细。",
                options: [
                    {
                        des: "'normal'",
                    },
                    {
                        des: "'bold'",
                    },
                    {
                        des: "'bolder'",
                    },
                    {
                        des: "'lighter'",
                    },
                ],
                propTypes: ["string", "number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 3,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "fontFamily",
                name: "fontFamily",
                description: "文字的字体系列。",
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 4,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "fontSize",
                name: "fontSize",
                description: "文字的字体大小。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 5,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "lineHeight",
                name: "lineHeight",
                description: "行高。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 6,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "backgroundColor",
                name: "backgroundColor",
                description: "文字块背景色。",
                options: [],
                propTypes: ["string", "object"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 7,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "borderColor",
                name: "borderColor",
                description: "文字块边框颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 8,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "borderWidth",
                name: "borderWidth",
                description: "文字块边框宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 9,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "borderType",
                name: "borderType",
                description: "文字块边框描边类型。",
                options: [
                    {
                        des: "'solid'",
                    },
                    {
                        des: "'dashed'",
                    },
                    {
                        des: "'dotted'",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 10,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "borderDashOffset",
                name: "borderDashOffset",
                description: "用于设置虚线的偏移量，可搭配 borderType 指定 dash array 实现灵活的虚线效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 11,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "borderRadius",
                name: "borderRadius",
                description: "文字块的圆角。",
                options: [],
                propTypes: ["number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 12,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "padding",
                name: "padding",
                description: "文字块的内边距。例如：",
                options: [
                    {
                        des: "padding: [3, 4, 5, 6]",
                    },
                    {
                        des: "padding: 4",
                    },
                    {
                        des: "padding: [3, 4]",
                    },
                ],
                propTypes: ["number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 13,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "shadowColor",
                name: "shadowColor",
                description: "文字块的背景阴影颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 14,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "shadowBlur",
                name: "shadowBlur",
                description: "文字块的背景阴影长度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 15,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "shadowOffsetX",
                name: "shadowOffsetX",
                description: "文字块的背景阴影 X 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 16,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "shadowOffsetY",
                name: "shadowOffsetY",
                description: "文字块的背景阴影 Y 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 17,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "width",
                name: "width",
                description: "文本显示宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 18,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "height",
                name: "height",
                description: "文本显示高度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 19,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "textBorderColor",
                name: "textBorderColor",
                description: "文字本身的描边颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 20,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "textBorderWidth",
                name: "textBorderWidth",
                description: "文字本身的描边宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 21,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "textBorderType",
                name: "textBorderType",
                description: "文字本身的描边类型。",
                options: [
                    {
                        des: "'solid'",
                    },
                    {
                        des: "'dashed'",
                    },
                    {
                        des: "'dotted'",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 22,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "textBorderDashOffset",
                name: "textBorderDashOffset",
                description: "用于设置虚线的偏移量，可搭配 textBorderType 指定 dash array 实现灵活的虚线效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 23,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "textShadowColor",
                name: "textShadowColor",
                description: "文字本身的阴影颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 24,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "textShadowBlur",
                name: "textShadowBlur",
                description: "文字本身的阴影长度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 25,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "textShadowOffsetX",
                name: "textShadowOffsetX",
                description: "文字本身的阴影 X 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 26,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "textShadowOffsetY",
                name: "textShadowOffsetY",
                description: "文字本身的阴影 Y 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 27,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "overflow",
                name: "overflow",
                description: "文字超出宽度是否截断或者换行。配置width时有效",
                options: [
                    {
                        des: "'truncate'",
                    },
                    {
                        des: "'break'",
                    },
                    {
                        des: "'breakAll'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 28,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "ellipsis",
                name: "ellipsis",
                description: "在overflow配置为'truncate'的时候，可以通过该属性配置末尾显示的文本。",
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 29,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "rich",
                name: "rich",
                description: "在 rich 里面，可以自定义富文本样式。利用富文本样式，可以在标签中做出非常丰富的效果。",
                options: [],
                propTypes: ["object"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 30,
                level: 3,
                parentPath: ["legend", "textStyle"],
                id: "richInheritPlainLabel",
                name: "richInheritPlainLabel",
                description: "富文本样式是否继承普通文本样式。",
                options: [],
                propTypes: ["boolean"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 34,
        level: 2,
        parentPath: ["legend"],
        id: "tooltip",
        name: "tooltip",
        description: "图例的 tooltip 配置，配置项同 tooltip。默认不显示，可以在 legend 文字很多的时候对文字做裁剪并且开启 tooltip，如下示例：",
        options: [],
        propTypes: ["object"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 35,
        level: 2,
        parentPath: ["legend"],
        id: "icon",
        name: "icon",
        description: "图例项的 icon。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 36,
        level: 2,
        parentPath: ["legend"],
        id: "data",
        name: "data",
        description:
            "图例的数据数组。数组项通常为一个字符串，每一项代表一个系列的 name（如果是饼图，也可以是饼图单个数据的 name）。图例组件会自动根据对应系列的图形标记（symbol）来绘制自己的颜色和标记，特殊字符串 ''（空字符串）或者 '\\n'（换行字符串）用于图例的换行。",
        options: [],
        propTypes: ["array"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 37,
        level: 2,
        parentPath: ["legend"],
        id: "backgroundColor",
        name: "backgroundColor",
        description: "图例背景色，默认透明。",
        options: [],
        propTypes: ["color"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 38,
        level: 2,
        parentPath: ["legend"],
        id: "borderColor",
        name: "borderColor",
        description: "图例的边框颜色。支持的颜色格式同 backgroundColor。",
        options: [],
        propTypes: ["color"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 39,
        level: 2,
        parentPath: ["legend"],
        id: "borderWidth",
        name: "borderWidth",
        description: "图例的边框线宽。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 40,
        level: 2,
        parentPath: ["legend"],
        id: "borderRadius",
        name: "borderRadius",
        description: "圆角半径，单位px，支持传入数组分别指定 4 个圆角半径。 如:",
        options: [],
        propTypes: ["number", "array"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 41,
        level: 2,
        parentPath: ["legend"],
        id: "shadowBlur",
        name: "shadowBlur",
        description: "图形阴影的模糊大小。该属性配合 shadowColor,shadowOffsetX, shadowOffsetY 一起设置图形的阴影效果。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 42,
        level: 2,
        parentPath: ["legend"],
        id: "shadowColor",
        name: "shadowColor",
        description: "阴影颜色。支持的格式同color。",
        options: [],
        propTypes: ["color"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 43,
        level: 2,
        parentPath: ["legend"],
        id: "shadowOffsetX",
        name: "shadowOffsetX",
        description: "阴影水平方向上的偏移距离。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 44,
        level: 2,
        parentPath: ["legend"],
        id: "shadowOffsetY",
        name: "shadowOffsetY",
        description: "阴影垂直方向上的偏移距离。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 45,
        level: 2,
        parentPath: ["legend"],
        id: "scrollDataIndex",
        name: "scrollDataIndex",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 46,
        level: 2,
        parentPath: ["legend"],
        id: "pageButtonItemGap",
        name: "pageButtonItemGap",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 47,
        level: 2,
        parentPath: ["legend"],
        id: "pageButtonGap",
        name: "pageButtonGap",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 48,
        level: 2,
        parentPath: ["legend"],
        id: "pageButtonPosition",
        name: "pageButtonPosition",
        description: "legend.type 为 'scroll' 时有效。",
        options: [
            {
                des: "'start'",
            },
            {
                des: "'end'",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 49,
        level: 2,
        parentPath: ["legend"],
        id: "pageFormatter",
        name: "pageFormatter",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["string", "function"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 50,
        level: 2,
        parentPath: ["legend"],
        id: "pageIcons",
        name: "pageIcons",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["legend", "pageIcons"],
                id: "horizontal",
                name: "horizontal",
                description: "legend.orient 为 'horizontal' 时的翻页按钮图标。",
                options: [],
                propTypes: ["array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 1,
                level: 3,
                parentPath: ["legend", "pageIcons"],
                id: "vertical",
                name: "vertical",
                description: "legend.orient 为 'vertical' 时的翻页按钮图标。",
                options: [],
                propTypes: ["array"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 51,
        level: 2,
        parentPath: ["legend"],
        id: "pageIconColor",
        name: "pageIconColor",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 52,
        level: 2,
        parentPath: ["legend"],
        id: "pageIconInactiveColor",
        name: "pageIconInactiveColor",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 53,
        level: 2,
        parentPath: ["legend"],
        id: "pageIconSize",
        name: "pageIconSize",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["number", "array"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 54,
        level: 2,
        parentPath: ["legend"],
        id: "pageTextStyle",
        name: "pageTextStyle",
        description: "legend.type 为 'scroll' 时有效。",
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "color",
                name: "color",
                description: "文字的颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 1,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "fontStyle",
                name: "fontStyle",
                description: "文字字体的风格。",
                options: [
                    {
                        des: "'normal'",
                    },
                    {
                        des: "'italic'",
                    },
                    {
                        des: "'oblique'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 2,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "fontWeight",
                name: "fontWeight",
                description: "文字字体的粗细。",
                options: [
                    {
                        des: "'normal'",
                    },
                    {
                        des: "'bold'",
                    },
                    {
                        des: "'bolder'",
                    },
                    {
                        des: "'lighter'",
                    },
                ],
                propTypes: ["string", "number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 3,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "fontFamily",
                name: "fontFamily",
                description: "文字的字体系列。",
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 4,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "fontSize",
                name: "fontSize",
                description: "文字的字体大小。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 5,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "lineHeight",
                name: "lineHeight",
                description: "行高。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 6,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "width",
                name: "width",
                description: "文本显示宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 7,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "height",
                name: "height",
                description: "文本显示高度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 8,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "textBorderColor",
                name: "textBorderColor",
                description: "文字本身的描边颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 9,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "textBorderWidth",
                name: "textBorderWidth",
                description: "文字本身的描边宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 10,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "textBorderType",
                name: "textBorderType",
                description: "文字本身的描边类型。",
                options: [
                    {
                        des: "'solid'",
                    },
                    {
                        des: "'dashed'",
                    },
                    {
                        des: "'dotted'",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 11,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "textBorderDashOffset",
                name: "textBorderDashOffset",
                description: "用于设置虚线的偏移量，可搭配 textBorderType 指定 dash array 实现灵活的虚线效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 12,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "textShadowColor",
                name: "textShadowColor",
                description: "文字本身的阴影颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 13,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "textShadowBlur",
                name: "textShadowBlur",
                description: "文字本身的阴影长度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 14,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "textShadowOffsetX",
                name: "textShadowOffsetX",
                description: "文字本身的阴影 X 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 15,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "textShadowOffsetY",
                name: "textShadowOffsetY",
                description: "文字本身的阴影 Y 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 16,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "overflow",
                name: "overflow",
                description: "文字超出宽度是否截断或者换行。配置width时有效",
                options: [
                    {
                        des: "'truncate'",
                    },
                    {
                        des: "'break'",
                    },
                    {
                        des: "'breakAll'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 17,
                level: 3,
                parentPath: ["legend", "pageTextStyle"],
                id: "ellipsis",
                name: "ellipsis",
                description: "在overflow配置为'truncate'的时候，可以通过该属性配置末尾显示的文本。",
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 55,
        level: 2,
        parentPath: ["legend"],
        id: "animation",
        name: "animation",
        description: "图例翻页是否使用动画。",
        options: [],
        propTypes: ["boolean"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 56,
        level: 2,
        parentPath: ["legend"],
        id: "animationDurationUpdate",
        name: "animationDurationUpdate",
        description: "图例翻页时的动画时长。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 57,
        level: 2,
        parentPath: ["legend"],
        id: "emphasis",
        name: "emphasis",
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["legend", "emphasis"],
                id: "selectorLabel",
                name: "selectorLabel",
                options: [],
                propTypes: ["object"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 58,
        level: 2,
        parentPath: ["legend"],
        id: "selector",
        name: "selector",
        description: "图例组件中的选择器按钮，目前包括“全选”和“反选”两种功能。默认不显示，用户可手动开启，也可以手动配置每个按钮的标题。",
        options: [],
        propTypes: ["boolean", "array"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 59,
        level: 2,
        parentPath: ["legend"],
        id: "selectorLabel",
        name: "selectorLabel",
        description: "选择器按钮的文本标签样式，默认显示。",
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "show",
                name: "show",
                description: "是否显示标签。",
                options: [],
                propTypes: ["boolean"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 1,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "distance",
                name: "distance",
                description: "距离图形元素的距离。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 2,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "rotate",
                name: "rotate",
                description: "标签旋转。从 -90 度到 90 度。正值是逆时针。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 3,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "offset",
                name: "offset",
                description: "是否对文字进行偏移。默认不偏移。例如：[30, 40] 表示文字在横向上偏移 30，纵向上偏移 40。",
                options: [],
                propTypes: ["array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 4,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "color",
                name: "color",
                description: "文字的颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 5,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "fontStyle",
                name: "fontStyle",
                description: "文字字体的风格。",
                options: [
                    {
                        des: "'normal'",
                    },
                    {
                        des: "'italic'",
                    },
                    {
                        des: "'oblique'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 6,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "fontWeight",
                name: "fontWeight",
                description: "文字字体的粗细。",
                options: [
                    {
                        des: "'normal'",
                    },
                    {
                        des: "'bold'",
                    },
                    {
                        des: "'bolder'",
                    },
                    {
                        des: "'lighter'",
                    },
                ],
                propTypes: ["string", "number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 7,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "fontFamily",
                name: "fontFamily",
                description: "文字的字体系列。",
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 8,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "fontSize",
                name: "fontSize",
                description: "文字的字体大小。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 9,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "align",
                name: "align",
                description: "文字水平对齐方式，默认自动。",
                options: [
                    {
                        des: "'left'",
                    },
                    {
                        des: "'center'",
                    },
                    {
                        des: "'right'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 10,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "verticalAlign",
                name: "verticalAlign",
                description: "文字垂直对齐方式，默认自动。",
                options: [
                    {
                        des: "'top'",
                    },
                    {
                        des: "'middle'",
                    },
                    {
                        des: "'bottom'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 11,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "lineHeight",
                name: "lineHeight",
                description: "行高。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 12,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "backgroundColor",
                name: "backgroundColor",
                description: "文字块背景色。",
                options: [],
                propTypes: ["string", "object"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 13,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "borderColor",
                name: "borderColor",
                description: "文字块边框颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 14,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "borderWidth",
                name: "borderWidth",
                description: "文字块边框宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 15,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "borderType",
                name: "borderType",
                description: "文字块边框描边类型。",
                options: [
                    {
                        des: "'solid'",
                    },
                    {
                        des: "'dashed'",
                    },
                    {
                        des: "'dotted'",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 16,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "borderDashOffset",
                name: "borderDashOffset",
                description: "用于设置虚线的偏移量，可搭配 borderType 指定 dash array 实现灵活的虚线效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 17,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "borderRadius",
                name: "borderRadius",
                description: "文字块的圆角。",
                options: [],
                propTypes: ["number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 18,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "padding",
                name: "padding",
                description: "文字块的内边距。例如：",
                options: [
                    {
                        des: "padding: [3, 4, 5, 6]",
                    },
                    {
                        des: "padding: 4",
                    },
                    {
                        des: "padding: [3, 4]",
                    },
                ],
                propTypes: ["number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 19,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "shadowColor",
                name: "shadowColor",
                description: "文字块的背景阴影颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 20,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "shadowBlur",
                name: "shadowBlur",
                description: "文字块的背景阴影长度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 21,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "shadowOffsetX",
                name: "shadowOffsetX",
                description: "文字块的背景阴影 X 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 22,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "shadowOffsetY",
                name: "shadowOffsetY",
                description: "文字块的背景阴影 Y 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 23,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "width",
                name: "width",
                description: "文本显示宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 24,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "height",
                name: "height",
                description: "文本显示高度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 25,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "textBorderColor",
                name: "textBorderColor",
                description: "文字本身的描边颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 26,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "textBorderWidth",
                name: "textBorderWidth",
                description: "文字本身的描边宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 27,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "textBorderType",
                name: "textBorderType",
                description: "文字本身的描边类型。",
                options: [
                    {
                        des: "'solid'",
                    },
                    {
                        des: "'dashed'",
                    },
                    {
                        des: "'dotted'",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 28,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "textBorderDashOffset",
                name: "textBorderDashOffset",
                description: "用于设置虚线的偏移量，可搭配 textBorderType 指定 dash array 实现灵活的虚线效果。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 29,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "textShadowColor",
                name: "textShadowColor",
                description: "文字本身的阴影颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 30,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "textShadowBlur",
                name: "textShadowBlur",
                description: "文字本身的阴影长度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 31,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "textShadowOffsetX",
                name: "textShadowOffsetX",
                description: "文字本身的阴影 X 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 32,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "textShadowOffsetY",
                name: "textShadowOffsetY",
                description: "文字本身的阴影 Y 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 33,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "overflow",
                name: "overflow",
                description: "文字超出宽度是否截断或者换行。配置width时有效",
                options: [
                    {
                        des: "'truncate'",
                    },
                    {
                        des: "'break'",
                    },
                    {
                        des: "'breakAll'",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 34,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "ellipsis",
                name: "ellipsis",
                description: "在overflow配置为'truncate'的时候，可以通过该属性配置末尾显示的文本。",
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 35,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "rich",
                name: "rich",
                description: "在 rich 里面，可以自定义富文本样式。利用富文本样式，可以在标签中做出非常丰富的效果。",
                options: [],
                propTypes: ["object"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 36,
                level: 3,
                parentPath: ["legend", "selectorLabel"],
                id: "richInheritPlainLabel",
                name: "richInheritPlainLabel",
                description: "富文本样式是否继承普通文本样式。",
                options: [],
                propTypes: ["boolean"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 60,
        level: 2,
        parentPath: ["legend"],
        id: "selectorPosition",
        name: "selectorPosition",
        description:
            "选择器的位置，可以放在图例的尾部或者头部，对应的值分别为 'end' 和 'start'。默认情况下，图例横向布局的时候，选择器放在图例的尾部；图例纵向布局的时候，选择器放在图例的头部。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 61,
        level: 2,
        parentPath: ["legend"],
        id: "selectorItemGap",
        name: "selectorItemGap",
        description: "选择器按钮之间的间隔。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 62,
        level: 2,
        parentPath: ["legend"],
        id: "selectorButtonGap",
        name: "selectorButtonGap",
        description: "选择器按钮与图例组件之间的间隔。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 63,
        level: 2,
        parentPath: ["legend"],
        id: "triggerEvent",
        name: "triggerEvent",
        description: "是否触发事件。",
        options: [],
        propTypes: ["boolean"],
        descendant: [],
        isLeaf: true,
    },
];

export default legendConfig;
