import { EchartsTreeState } from "./config";

const TitleConfig: EchartsTreeState[] = [
    {
        sort: 0,
        id: "id",
        name: "id",
        nodeType: "string",
        isLeaf: true,
        level: 2,
        description: "组件 ID。默认不指定。指定则可用于在 option 或者 API 中引用组件。",
        descendant: [],
    },
    {
        sort: 1,
        id: "show",
        name: "show",
        nodeType: "boolean",
        isLeaf: true,
        level: 2,
        description: "是否显示标题组件。",
        descendant: [],
    },
    {
        sort: 1,
        id: "text",
        name: "text",
        nodeType: "string",
        isLeaf: true,
        level: 2,
        description: "主标题文本，支持使用 \n 换行。",
        descendant: [],
    },
    {
        sort: 1,
        id: "link",
        name: "link",
        nodeType: "string",
        isLeaf: true,
        level: 2,
        description: "主标题文本超链接。",
        descendant: [],
    },
    {
        sort: 1,
        id: "target",
        name: "target",
        nodeType: "string",
        isLeaf: true,
        level: 2,
        description: "指定窗口打开主标题超链接。",
        descendant: [],
    },
    {
        sort: 1,
        id: "textStyle",
        name: "textStyle",
        nodeType: "null",
        isLeaf: false,
        level: 2,
        description: "指定窗口打开主标题超链接。",
        descendant: [
            {
                sort: 1,
                id: "color",
                name: "color",
                nodeType: "options",
                isLeaf: true,
                level: 3,
                description: "主标题文字的颜色。",
                descendant: [],
            },
            {
                sort: 1,
                id: "fontStyle",
                name: "fontStyle",
                nodeType: "string",
                isLeaf: true,
                level: 3,
                description: "主标题文字字体的风格。",
                descendant: [],
            },
            {
                sort: 1,
                id: "fontStyleType",
                name: "fontStyleType",
                nodeType: "string",
                isLeaf: false,
                level: 3,
                description: "1主标题文字字体的风格。",
                descendant: [
                    {
                        sort: 1,
                        id: "fontStyleType1",
                        name: "fontStyleType1",
                        nodeType: "string",
                        isLeaf: true,
                        level: 4,
                        description: "2主标题文字字体的风格。",
                        descendant: [],
                    },
                ],
            },
        ],
    },
];

export default TitleConfig;
