export const WEB_TOKEN = "WEB_TOKEN";
export const COLLAPSED_MENU = "COLLAPSED_MENU";

export const TOKEN =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9zZW4iLCJ1c2VySWQiOiIiLCJpYXQiOjE2NDIzNDc0NzksImV4cCI6MTY0Mjc3OTQ3OX0.NPTuqvGdafUyX_zUsbSZQ-yoMOlpqJISEBxDg1Uoal4";
