export const WEB_TOKEN = "WEB_TOKEN";
export const COLLAPSED_MENU = "COLLAPSED_MENU";

export const TOKEN =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9zZW4iLCJ1c2VySWQiOiIiLCJpYXQiOjE2NDQ3MzcwOTcsImV4cCI6MTY0NTE2OTA5N30.Lzo4ANHKRn02CpdghQDcOf1tTuCtr8xr8-iOa60PJ5M";
