export const WEB_TOKEN = "WEB_TOKEN";
export const COLLAPSED_MENU = "COLLAPSED_MENU";

export const TOKEN =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9zZW4iLCJ1c2VySWQiOiIiLCJpYXQiOjE2NDI4MzM5MTAsImV4cCI6MTY0MzI2NTkxMH0.fuICcfMC-6ROpqCVUs7ncDrwWOlckUAI_dyNXhyqL6A";
