import { EchartsTreeState } from "./index";

const TitleConfig: EchartsTreeState[] = [
    {
        sort: 0,
        level: 2,
        parentPath: ["title"],
        id: "id",
        name: "id",
        defaultValue: "",
        shortDescroption: "组件 ID。默认不指定。指定则可用于在 option 或者 API 中引用组件。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 1,
        level: 2,
        parentPath: ["title"],
        id: "show",
        name: "show",
        defaultValue: "true",
        shortDescroption: "是否显示标题组件。",
        options: [],
        propTypes: ["boolean"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 2,
        level: 2,
        parentPath: ["title"],
        id: "text",
        name: "text",
        defaultValue: "",
        shortDescroption: "主标题文本，支持使用 \\n 换行。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 3,
        level: 2,
        parentPath: ["title"],
        id: "link",
        name: "link",
        defaultValue: "",
        shortDescroption: "主标题文本超链接。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 4,
        level: 2,
        parentPath: ["title"],
        id: "target",
        name: "target",
        defaultValue: "blank",
        shortDescroption: "指定窗口打开主标题超链接。",
        description: ["指定窗口打开主标题超链接。", "可选：", "'self' 当前窗口打开", "'blank' 新窗口打开"],
        options: [
            {
                key: "self",
                des: "self当前窗口打开",
            },
            {
                key: "blank",
                des: "blank新窗口打开",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 5,
        level: 2,
        parentPath: ["title"],
        id: "textStyle",
        name: "textStyle",
        defaultValue: "#333",
        shortDescroption: "主标题文字的颜色。",
        description: [],
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "color",
                name: "color",
                defaultValue: "#333",
                shortDescroption: "主标题文字的颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 1,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "fontStyle",
                name: "fontStyle",
                defaultValue: "normal",
                shortDescroption: "主标题文字字体的风格。",
                description: ["主标题文字字体的风格。", "可选："],
                options: [
                    {
                        key: "normal",
                        des: "normal",
                    },
                    {
                        key: "italic",
                        des: "italic",
                    },
                    {
                        key: "oblique",
                        des: "oblique",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 2,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "fontWeight",
                name: "fontWeight",
                defaultValue: "bolder",
                shortDescroption: "主标题文字字体的粗细。",
                description: ["主标题文字字体的粗细。", "可选："],
                options: [
                    {
                        key: "normal",
                        des: "normal",
                    },
                    {
                        key: "bold",
                        des: "bold",
                    },
                    {
                        key: "bolder",
                        des: "bolder",
                    },
                    {
                        key: "lighter",
                        des: "lighter",
                    },
                    {
                        key: "",
                        des: "100|200|300|400...",
                    },
                ],
                propTypes: ["string", "number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 3,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "fontFamily",
                name: "fontFamily",
                defaultValue: "sans-serif",
                shortDescroption: "主标题文字的字体系列。",
                description: ["主标题文字的字体系列。", "还可以是 'serif' , 'monospace', 'Arial', 'Courier New', 'Microsoft YaHei', ..."],
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 4,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "fontSize",
                name: "fontSize",
                defaultValue: "18",
                shortDescroption: "主标题文字的字体大小。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 5,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "lineHeight",
                name: "lineHeight",
                defaultValue: "",
                shortDescroption: "行高。",
                description: ["行高。", "rich 中如果没有设置 lineHeight，则会取父层级的 lineHeight。例如："],
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 6,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "width",
                name: "width",
                defaultValue: "",
                shortDescroption: "文本显示宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 7,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "height",
                name: "height",
                defaultValue: "",
                shortDescroption: "文本显示高度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 8,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "textBorderColor",
                name: "textBorderColor",
                defaultValue: "",
                shortDescroption: "文字本身的描边颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 9,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "textBorderWidth",
                name: "textBorderWidth",
                defaultValue: "",
                shortDescroption: "文字本身的描边宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 10,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "textBorderType",
                name: "textBorderType",
                defaultValue: "solid",
                shortDescroption: "文字本身的描边类型。",
                description: [
                    "文字本身的描边类型。",
                    "可选：",
                    "自 v5.0.0 开始，也可以是 number 或者 number 数组，用以指定线条的 dash array，配合 textBorderDashOffset 可实现更灵活的虚线效果。",
                    "例如：",
                ],
                options: [
                    {
                        key: "solid",
                        des: "solid",
                    },
                    {
                        key: "dashed",
                        des: "dashed",
                    },
                    {
                        key: "dotted",
                        des: "dotted",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 11,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "textBorderDashOffset",
                name: "textBorderDashOffset",
                defaultValue: "",
                shortDescroption: "用于设置虚线的偏移量，可搭配 textBorderType 指定 dash array 实现灵活的虚线效果。",
                description: [
                    "从 v5.0.0 开始支持",
                    "用于设置虚线的偏移量，可搭配 textBorderType 指定 dash array 实现灵活的虚线效果。",
                    "更多详情可以参考 MDN lineDashOffset。",
                ],
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 12,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "textShadowColor",
                name: "textShadowColor",
                defaultValue: "transparent",
                shortDescroption: "文字本身的阴影颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 13,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "textShadowBlur",
                name: "textShadowBlur",
                defaultValue: "",
                shortDescroption: "文字本身的阴影长度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 14,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "textShadowOffsetX",
                name: "textShadowOffsetX",
                defaultValue: "",
                shortDescroption: "文字本身的阴影 X 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 15,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "textShadowOffsetY",
                name: "textShadowOffsetY",
                defaultValue: "",
                shortDescroption: "文字本身的阴影 Y 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 16,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "overflow",
                name: "overflow",
                defaultValue: "none",
                shortDescroption: "文字超出宽度是否截断或者换行。配置width时有效",
                options: [
                    {
                        key: "truncate",
                        des: "truncate截断，并在末尾显示ellipsis配置的文本，默认为...",
                    },
                    {
                        key: "break",
                        des: "break换行",
                    },
                    {
                        key: "breakAll",
                        des: "breakAll换行，跟break不同的是，在英语等拉丁文中，breakAll还会强制单词内换行",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 17,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "ellipsis",
                name: "ellipsis",
                defaultValue: "...",
                shortDescroption: "在overflow配置为'truncate'的时候，可以通过该属性配置末尾显示的文本。",
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 18,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "rich",
                name: "rich",
                defaultValue: "",
                shortDescroption: "在 rich 里面，可以自定义富文本样式。利用富文本样式，可以在标签中做出非常丰富的效果。",
                description: ["在 rich 里面，可以自定义富文本样式。利用富文本样式，可以在标签中做出非常丰富的效果。", "例如：", "详情参见教程：富文本标签"],
                options: [],
                propTypes: ["object"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 19,
                level: 3,
                parentPath: ["title", "textStyle"],
                id: "richInheritPlainLabel",
                name: "richInheritPlainLabel",
                defaultValue: "true",
                shortDescroption: "富文本样式是否继承普通文本样式。",
                description: [
                    "从 v6.0.0 开始支持",
                    "富文本样式是否继承普通文本样式。",
                    "此配置项用于向历史兼容。",
                    "从 v6 版本开始，富文本标签 (label.rich / textStyle.rich) 部分样式（fontStyle, fontWeight, fontSize, fontFamily, textShadowColor, textShadowBlur, textShadowOffsetX, textShadowOffsetY）默认继承 普通文本样式 (label / textStyle)。你可以设置 richInheritPlainLabel: false （可在最外层配置项或与同级文本样式配置项）来禁用此行为。",
                ],
                options: [],
                propTypes: ["boolean"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 6,
        level: 2,
        parentPath: ["title"],
        id: "subtext",
        name: "subtext",
        defaultValue: "",
        shortDescroption: "副标题文本，支持使用 \\n 换行。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 7,
        level: 2,
        parentPath: ["title"],
        id: "sublink",
        name: "sublink",
        defaultValue: "",
        shortDescroption: "副标题文本超链接。",
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 8,
        level: 2,
        parentPath: ["title"],
        id: "subtarget",
        name: "subtarget",
        defaultValue: "blank",
        shortDescroption: "指定窗口打开副标题超链接，可选：",
        description: ["指定窗口打开副标题超链接，可选：", "'self' 当前窗口打开", "'blank' 新窗口打开"],
        options: [
            {
                key: "self",
                des: "self当前窗口打开",
            },
            {
                key: "blank",
                des: "blank新窗口打开",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 9,
        level: 2,
        parentPath: ["title"],
        id: "subtextStyle",
        name: "subtextStyle",
        defaultValue: "#aaa",
        shortDescroption: "副标题文字的颜色。",
        description: [],
        options: [],
        propTypes: ["object"],
        descendant: [
            {
                sort: 0,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "color",
                name: "color",
                defaultValue: "#aaa",
                shortDescroption: "副标题文字的颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 1,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "fontStyle",
                name: "fontStyle",
                defaultValue: "normal",
                shortDescroption: "副标题文字字体的风格。",
                description: ["副标题文字字体的风格。", "可选："],
                options: [
                    {
                        key: "normal",
                        des: "normal",
                    },
                    {
                        key: "italic",
                        des: "italic",
                    },
                    {
                        key: "oblique",
                        des: "oblique",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 2,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "fontWeight",
                name: "fontWeight",
                defaultValue: "normal",
                shortDescroption: "副标题文字字体的粗细。",
                description: ["副标题文字字体的粗细。", "可选："],
                options: [
                    {
                        key: "normal",
                        des: "normal",
                    },
                    {
                        key: "bold",
                        des: "bold",
                    },
                    {
                        key: "bolder",
                        des: "bolder",
                    },
                    {
                        key: "lighter",
                        des: "lighter",
                    },
                    {
                        key: "",
                        des: "100|200|300|400...",
                    },
                ],
                propTypes: ["string", "number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 3,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "fontFamily",
                name: "fontFamily",
                defaultValue: "sans-serif",
                shortDescroption: "副标题文字的字体系列。",
                description: ["副标题文字的字体系列。", "还可以是 'serif' , 'monospace', 'Arial', 'Courier New', 'Microsoft YaHei', ..."],
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 4,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "fontSize",
                name: "fontSize",
                defaultValue: "12",
                shortDescroption: "副标题文字的字体大小。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 5,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "align",
                name: "align",
                defaultValue: "",
                shortDescroption: "文字水平对齐方式，默认自动。",
                description: ["文字水平对齐方式，默认自动。", "可选：", "rich 中如果没有设置 align，则会取父层级的 align。例如："],
                options: [
                    {
                        key: "left",
                        des: "left",
                    },
                    {
                        key: "center",
                        des: "center",
                    },
                    {
                        key: "right",
                        des: "right",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 6,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "verticalAlign",
                name: "verticalAlign",
                defaultValue: "",
                shortDescroption: "文字垂直对齐方式，默认自动。",
                description: ["文字垂直对齐方式，默认自动。", "可选：", "rich 中如果没有设置 verticalAlign，则会取父层级的 verticalAlign。例如："],
                options: [
                    {
                        key: "top",
                        des: "top",
                    },
                    {
                        key: "middle",
                        des: "middle",
                    },
                    {
                        key: "bottom",
                        des: "bottom",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 7,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "lineHeight",
                name: "lineHeight",
                defaultValue: "",
                shortDescroption: "行高。",
                description: ["行高。", "rich 中如果没有设置 lineHeight，则会取父层级的 lineHeight。例如："],
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 8,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "width",
                name: "width",
                defaultValue: "",
                shortDescroption: "文本显示宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 9,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "height",
                name: "height",
                defaultValue: "",
                shortDescroption: "文本显示高度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 10,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "textBorderColor",
                name: "textBorderColor",
                defaultValue: "",
                shortDescroption: "文字本身的描边颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 11,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "textBorderWidth",
                name: "textBorderWidth",
                defaultValue: "",
                shortDescroption: "文字本身的描边宽度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 12,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "textBorderType",
                name: "textBorderType",
                defaultValue: "solid",
                shortDescroption: "文字本身的描边类型。",
                description: [
                    "文字本身的描边类型。",
                    "可选：",
                    "自 v5.0.0 开始，也可以是 number 或者 number 数组，用以指定线条的 dash array，配合 textBorderDashOffset 可实现更灵活的虚线效果。",
                    "例如：",
                ],
                options: [
                    {
                        key: "solid",
                        des: "solid",
                    },
                    {
                        key: "dashed",
                        des: "dashed",
                    },
                    {
                        key: "dotted",
                        des: "dotted",
                    },
                ],
                propTypes: ["string", "number", "array"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 13,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "textBorderDashOffset",
                name: "textBorderDashOffset",
                defaultValue: "",
                shortDescroption: "用于设置虚线的偏移量，可搭配 textBorderType 指定 dash array 实现灵活的虚线效果。",
                description: [
                    "从 v5.0.0 开始支持",
                    "用于设置虚线的偏移量，可搭配 textBorderType 指定 dash array 实现灵活的虚线效果。",
                    "更多详情可以参考 MDN lineDashOffset。",
                ],
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 14,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "textShadowColor",
                name: "textShadowColor",
                defaultValue: "transparent",
                shortDescroption: "文字本身的阴影颜色。",
                options: [],
                propTypes: ["color"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 15,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "textShadowBlur",
                name: "textShadowBlur",
                defaultValue: "",
                shortDescroption: "文字本身的阴影长度。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 16,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "textShadowOffsetX",
                name: "textShadowOffsetX",
                defaultValue: "",
                shortDescroption: "文字本身的阴影 X 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 17,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "textShadowOffsetY",
                name: "textShadowOffsetY",
                defaultValue: "",
                shortDescroption: "文字本身的阴影 Y 偏移。",
                options: [],
                propTypes: ["number"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 18,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "overflow",
                name: "overflow",
                defaultValue: "none",
                shortDescroption: "文字超出宽度是否截断或者换行。配置width时有效",
                options: [
                    {
                        key: "truncate",
                        des: "truncate截断，并在末尾显示ellipsis配置的文本，默认为...",
                    },
                    {
                        key: "break",
                        des: "break换行",
                    },
                    {
                        key: "breakAll",
                        des: "breakAll换行，跟break不同的是，在英语等拉丁文中，breakAll还会强制单词内换行",
                    },
                ],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 19,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "ellipsis",
                name: "ellipsis",
                defaultValue: "...",
                shortDescroption: "在overflow配置为'truncate'的时候，可以通过该属性配置末尾显示的文本。",
                options: [],
                propTypes: ["string"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 20,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "rich",
                name: "rich",
                defaultValue: "",
                shortDescroption: "在 rich 里面，可以自定义富文本样式。利用富文本样式，可以在标签中做出非常丰富的效果。",
                description: ["在 rich 里面，可以自定义富文本样式。利用富文本样式，可以在标签中做出非常丰富的效果。", "例如：", "详情参见教程：富文本标签"],
                options: [],
                propTypes: ["object"],
                descendant: [],
                isLeaf: true,
            },
            {
                sort: 21,
                level: 3,
                parentPath: ["title", "subtextStyle"],
                id: "richInheritPlainLabel",
                name: "richInheritPlainLabel",
                defaultValue: "true",
                shortDescroption: "富文本样式是否继承普通文本样式。",
                description: [
                    "从 v6.0.0 开始支持",
                    "富文本样式是否继承普通文本样式。",
                    "此配置项用于向历史兼容。",
                    "从 v6 版本开始，富文本标签 (label.rich / textStyle.rich) 部分样式（fontStyle, fontWeight, fontSize, fontFamily, textShadowColor, textShadowBlur, textShadowOffsetX, textShadowOffsetY）默认继承 普通文本样式 (label / textStyle)。你可以设置 richInheritPlainLabel: false （可在最外层配置项或与同级文本样式配置项）来禁用此行为。",
                ],
                options: [],
                propTypes: ["boolean"],
                descendant: [],
                isLeaf: true,
            },
        ],
        isLeaf: false,
    },
    {
        sort: 10,
        level: 2,
        parentPath: ["title"],
        id: "textAlign",
        name: "textAlign",
        defaultValue: "auto",
        shortDescroption: "整体（包括 text 和 subtext）的水平对齐。",
        description: ["整体（包括 text 和 subtext）的水平对齐。", "可选值：'auto'、'left'、'right'、'center'。"],
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 11,
        level: 2,
        parentPath: ["title"],
        id: "textVerticalAlign",
        name: "textVerticalAlign",
        defaultValue: "auto",
        shortDescroption: "整体（包括 text 和 subtext）的垂直对齐。",
        description: ["整体（包括 text 和 subtext）的垂直对齐。", "可选值：'auto'、'top'、'bottom'、'middle'。"],
        options: [],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 12,
        level: 2,
        parentPath: ["title"],
        id: "triggerEvent",
        name: "triggerEvent",
        defaultValue: "",
        shortDescroption: "是否触发事件。",
        options: [],
        propTypes: ["boolean"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 13,
        level: 2,
        parentPath: ["title"],
        id: "padding",
        name: "padding",
        defaultValue: "5",
        shortDescroption: "标题内边距，单位px，默认各方向内边距为5，接受数组分别设定上右下左边距。",
        description: ["标题内边距，单位px，默认各方向内边距为5，接受数组分别设定上右下左边距。", "使用示例："],
        options: [],
        propTypes: ["number", "array"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 14,
        level: 2,
        parentPath: ["title"],
        id: "itemGap",
        name: "itemGap",
        defaultValue: "10",
        shortDescroption: "主副标题之间的间距。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 15,
        level: 2,
        parentPath: ["title"],
        id: "zlevel",
        name: "zlevel",
        defaultValue: "",
        shortDescroption: "所有图形的 zlevel 值。",
        description: [
            "所有图形的 zlevel 值。",
            "zlevel用于 Canvas 分层，不同zlevel值的图形会放置在不同的 Canvas 中，Canvas 分层是一种常见的优化手段。我们可以把一些图形变化频繁（例如有动画）的组件设置成一个单独的zlevel。需要注意的是过多的 Canvas 会引起内存开销的增大，在手机端上需要谨慎使用以防崩溃。",
            "zlevel 大的 Canvas 会放在 zlevel 小的 Canvas 的上面。",
        ],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 16,
        level: 2,
        parentPath: ["title"],
        id: "z",
        name: "z",
        defaultValue: "2",
        shortDescroption: "组件的所有图形的z值。控制图形的前后顺序。z值小的图形会被z值大的图形覆盖。",
        description: ["组件的所有图形的z值。控制图形的前后顺序。z值小的图形会被z值大的图形覆盖。", "z相比zlevel优先级更低，而且不会创建新的 Canvas。"],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 17,
        level: 2,
        parentPath: ["title"],
        id: "left",
        name: "left",
        defaultValue: "auto",
        shortDescroption: "标题（title）组件离容器左侧的距离。",
        description: [
            "标题（title）组件离容器左侧的距离。",
            "left 的值可以是像 20 这样的具体像素值，可以是像 '20%' 这样相对于容器宽度的百分比，也可以是 'left', 'center', 'right'。",
            "如果 left 的值为 'left', 'center', 'right'，组件会根据相应的位置自动对齐。",
        ],
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 18,
        level: 2,
        parentPath: ["title"],
        id: "top",
        name: "top",
        defaultValue: "auto",
        shortDescroption: "标题（title）组件离容器上侧的距离。",
        description: [
            "标题（title）组件离容器上侧的距离。",
            "top 的值可以是像 20 这样的具体像素值，可以是像 '20%' 这样相对于容器高度的百分比，也可以是 'top', 'middle', 'bottom'。",
            "如果 top 的值为 'top', 'middle', 'bottom'，组件会根据相应的位置自动对齐。",
        ],
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 19,
        level: 2,
        parentPath: ["title"],
        id: "right",
        name: "right",
        defaultValue: "auto",
        shortDescroption: "标题（title）组件离容器右侧的距离。",
        description: [
            "标题（title）组件离容器右侧的距离。",
            "right 的值可以是像 20 这样的具体像素值，可以是像 '20%' 这样相对于容器宽度的百分比。",
            "默认自适应。",
        ],
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 20,
        level: 2,
        parentPath: ["title"],
        id: "bottom",
        name: "bottom",
        defaultValue: "auto",
        shortDescroption: "标题（title）组件离容器下侧的距离。",
        description: [
            "标题（title）组件离容器下侧的距离。",
            "bottom 的值可以是像 20 这样的具体像素值，可以是像 '20%' 这样相对于容器高度的百分比。",
            "默认自适应。",
        ],
        options: [],
        propTypes: ["string", "number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 21,
        level: 2,
        parentPath: ["title"],
        id: "coordinateSystem",
        name: "coordinateSystem",
        defaultValue: "none",
        shortDescroption: "指定另一个坐标系组件，本 title 布局在那个坐标系中。",
        description: [
            "从 v6.0.0 开始支持",
            "指定另一个坐标系组件，本 title 布局在那个坐标系中。",
            "可选值：",
            "null、undefined 或者 'none'",
            "不布局在任何坐标系中。自己独立完成布局。",
            "'calendar'",
            "布局在一个 日历坐标系 中。当一个 ECharts 实例中存在多个日历坐标系时，须通过 calendarIndex 或 calendarId 指定所使用的日历坐标系。",
            "'matrix'",
            "布局在一个 矩阵坐标系中。当一个 ECharts 实例中存在多个矩阵坐标系时，须通过 matrixIndex 或 matrixId 指定所使用的矩阵坐标系。",
            "下表总结了“某系列或组件是否支持布局在某坐标系上”：",
            "最左列列出了要布局的系列和组件（坐标系本身也是组件），最上行列出了所基于的坐标系。",
            "也参见 title.coordinateSystemUsage。",
        ],
        options: [
            {
                key: "null",
                des: "null、undefined或者none",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 22,
        level: 2,
        parentPath: ["title"],
        id: "coordinateSystemUsage",
        name: "coordinateSystemUsage",
        defaultValue: "box",
        shortDescroption: "如何在指定的 坐标系 上布局本 title。",
        description: [
            "从 v6.0.0 开始支持",
            "如何在指定的 坐标系 上布局本 title。",
            "在大多数情况下，无需显式指定 coordinateSystemUsage，除非默认行为不符合预期。",
            "可选值：",
            "'data'：（不适用于 title）",
            "此系列的每个数据项（例如，每个 series.data[i]）将独立地在指定的坐标系进行布局。 注：当前没有任何“非系列组件”支持 coordinateSystemUsage: 'data'。",
            "'box'：",
            "此系列或组件作为一个整体，在指定的坐标系中进行布局——即根据坐标系计算整体的包围盒或基础锚点。",
            "另参考：title.coordinateSystem。",
        ],
        options: [
            {
                key: "data",
                des: "data：（不适用于title）",
            },
            {
                key: "box",
                des: "box：",
            },
            {
                key: "",
                des: "例如，grid组件可以布局在matrix坐标系或calendar坐标系中，这时其布局矩形是由title.coords在坐标系中计算出来的。参见示例：矩阵中的小型直角坐标系。",
            },
            {
                key: "",
                des: "又如，饼图系列或和弦图系列可以布局在geo坐标系或cartesian2d坐标系中，这时其中心点是由series-pie.coords或series-pie.center在坐标系中计算出来的。参见示例：地理坐标系中的饼图。",
            },
        ],
        propTypes: ["string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 23,
        level: 2,
        parentPath: ["title"],
        id: "coord",
        name: "coord",
        defaultValue: "",
        shortDescroption: "当 coordinateSystemUsage 为 'box' 时, coord 被输入给坐标系，计算得到布局位置（布局盒或者中心点）。",
        description: [
            "从 v6.0.0 开始支持",
            "当 coordinateSystemUsage 为 'box' 时, coord 被输入给坐标系，计算得到布局位置（布局盒或者中心点）。",
            "例子：微型直角坐标系矩阵, 矩阵中的关系图.",
            "注：当 coordinateSystemUsage 为 'data' 时，输入给坐标系的是 series.data[i] 而非此 coord。",
        ],
        options: [],
        propTypes: ["array", "string"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 24,
        level: 2,
        parentPath: ["title"],
        id: "calendarIndex",
        name: "calendarIndex",
        defaultValue: "",
        shortDescroption: "布局时所基于的 日历坐标系 的 index。当一个 ECharts 实例中存在多个日历坐标系时，用其指定所使用的坐标系。",
        description: ["从 v6.0.0 开始支持", "布局时所基于的 日历坐标系 的 index。当一个 ECharts 实例中存在多个日历坐标系时，用其指定所使用的坐标系。"],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 25,
        level: 2,
        parentPath: ["title"],
        id: "calendarId",
        name: "calendarId",
        defaultValue: "undefined",
        shortDescroption: "布局时所基于的 日历坐标系 的 id。当一个 ECharts 实例中存在多个日历坐标系时，用其指定所使用的坐标系。",
        description: ["从 v6.0.0 开始支持", "布局时所基于的 日历坐标系 的 id。当一个 ECharts 实例中存在多个日历坐标系时，用其指定所使用的坐标系。"],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 26,
        level: 2,
        parentPath: ["title"],
        id: "matrixIndex",
        name: "matrixIndex",
        defaultValue: "",
        shortDescroption: "布局时所基于的 矩阵坐标系 的 index。当一个 ECharts 实例中存在多个矩阵坐标系时，用其指定所使用的坐标系。",
        description: ["从 v6.0.0 开始支持", "布局时所基于的 矩阵坐标系 的 index。当一个 ECharts 实例中存在多个矩阵坐标系时，用其指定所使用的坐标系。"],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 27,
        level: 2,
        parentPath: ["title"],
        id: "matrixId",
        name: "matrixId",
        defaultValue: "undefined",
        shortDescroption: "布局时所基于的 矩阵坐标系 的 id。当一个 ECharts 实例中存在多个矩阵坐标系时，用其指定所使用的坐标系。",
        description: ["从 v6.0.0 开始支持", "布局时所基于的 矩阵坐标系 的 id。当一个 ECharts 实例中存在多个矩阵坐标系时，用其指定所使用的坐标系。"],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 28,
        level: 2,
        parentPath: ["title"],
        id: "backgroundColor",
        name: "backgroundColor",
        defaultValue: "transparent",
        shortDescroption: "标题背景色，默认透明。",
        description: [
            "标题背景色，默认透明。",
            "颜色可以使用 RGB 表示，比如 'rgb(128, 128, 128)' ，如果想要加上 alpha 通道，可以使用 RGBA，比如 'rgba(128, 128, 128, 0.5)'，也可以使用十六进制格式，比如 '#ccc'",
        ],
        options: [],
        propTypes: ["color"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 29,
        level: 2,
        parentPath: ["title"],
        id: "borderColor",
        name: "borderColor",
        defaultValue: "#ccc",
        shortDescroption: "标题的边框颜色。支持的颜色格式同 backgroundColor。",
        options: [],
        propTypes: ["color"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 30,
        level: 2,
        parentPath: ["title"],
        id: "borderWidth",
        name: "borderWidth",
        defaultValue: "",
        shortDescroption: "标题的边框线宽。",
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 31,
        level: 2,
        parentPath: ["title"],
        id: "borderRadius",
        name: "borderRadius",
        defaultValue: "",
        shortDescroption: "圆角半径，单位px，支持传入数组分别指定 4 个圆角半径。 如:",
        options: [],
        propTypes: ["number", "array"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 32,
        level: 2,
        parentPath: ["title"],
        id: "shadowBlur",
        name: "shadowBlur",
        defaultValue: "",
        shortDescroption: "图形阴影的模糊大小。该属性配合 shadowColor,shadowOffsetX, shadowOffsetY 一起设置图形的阴影效果。",
        description: [
            "图形阴影的模糊大小。该属性配合 shadowColor,shadowOffsetX, shadowOffsetY 一起设置图形的阴影效果。",
            "示例：",
            "注意：此配置项生效的前提是，设置了 show: true 以及值不为 transparent 的背景色 backgroundColor。",
        ],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 33,
        level: 2,
        parentPath: ["title"],
        id: "shadowColor",
        name: "shadowColor",
        defaultValue: "",
        shortDescroption: "阴影颜色。支持的格式同color。",
        description: ["阴影颜色。支持的格式同color。", "注意：此配置项生效的前提是，设置了 show: true。"],
        options: [],
        propTypes: ["color"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 34,
        level: 2,
        parentPath: ["title"],
        id: "shadowOffsetX",
        name: "shadowOffsetX",
        defaultValue: "",
        shortDescroption: "阴影水平方向上的偏移距离。",
        description: ["阴影水平方向上的偏移距离。", "注意：此配置项生效的前提是，设置了 show: true。"],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
    {
        sort: 35,
        level: 2,
        parentPath: ["title"],
        id: "shadowOffsetY",
        name: "shadowOffsetY",
        defaultValue: "",
        shortDescroption: "阴影垂直方向上的偏移距离。",
        description: ["阴影垂直方向上的偏移距离。", "注意：此配置项生效的前提是，设置了 show: true。"],
        options: [],
        propTypes: ["number"],
        descendant: [],
        isLeaf: true,
    },
];

export default TitleConfig;
