export const col = [
    {
        id: "1567038254908198913",
        code: "s/waybill",
        visible: true,
        width: 180,
        export: true,
        title: "运单号",
        type: 4,
        propKey: "transportOrderNumber",
        idx: 0,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038254937559042",
        code: "s/waybill",
        visible: true,
        width: 130,
        export: true,
        title: "冷云面单号",
        type: 1,
        propKey: "paperyFaceListNumber",
        idx: 1,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038254966919170",
        code: "s/waybill",
        visible: true,
        width: 200,
        export: true,
        title: "客户名称",
        type: 1,
        propKey: "clientName",
        idx: 2,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["select"]}],"selectOption":{"key":"id","value":"customerFullName","url":"/common/customerBasicInformation/advanced-page"},"remoteOption":{"selectType":2,"keyName":"id","mode":"multiple"},"queKey":"clientId"}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038254983696385",
        code: "s/waybill",
        visible: true,
        width: 110,
        export: true,
        title: "运单状态",
        type: 2,
        propKey: "status",
        idx: 3,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["staticOptions"]}],"staticOptions":[{"key":1,"value":"待提交","style":{"color":"#3291f8"}},{"key":2,"value":"已确认","style":{"color":"#801dae"}},{"key":3,"value":"运输中","style":{"color":"#ffa400"}},{"key":4,"value":"待签收","style":{"color":"#2edfa3"}},{"key":5,"value":"已签收","style":{"color":"#52C41A"}},{"key":6,"value":"已取消","style":{"color":"#ff3300"}},{"key":7,"value":"已提交","style":{"color":"#ca6924"}},{"key":8,"value":"待确认","style":{"color":"#a98175"}},{"key":9,"value":"拒签","style":{"color":"red"}}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255004667906",
        code: "s/waybill",
        visible: true,
        width: 110,
        export: true,
        title: "运单类型",
        type: 2,
        propKey: "orderType",
        idx: 4,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["staticOptions"]}],"staticOptions":[{"key":1,"value":"国内业务"},{"key":2,"value":"国际业务"}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255042416642",
        code: "s/waybill",
        visible: true,
        width: 120,
        export: true,
        title: "运输模式",
        type: 1,
        propKey: "transportMethodCode",
        idx: 5,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["staticOptions"]}],"staticOptions":[{"key":"TRANSPORTATION_MODE_LD","value":"零担","style":{"color":"#5cdbd3"}},{"key":"TRANSPORTATION_MODE_ZC","value":"整车","style":{"color":"#08979c"}}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255063388161",
        code: "s/waybill",
        visible: true,
        width: 130,
        export: true,
        title: "取件需求车型",
        type: 4,
        propKey: "updateUserId",
        idx: 6,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}],"queKey":"senders.privateCarName"}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255092748290",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "计划取件时间",
        type: 4,
        propKey: "projectId",
        idx: 7,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["timeInterval"]}],"queKey":"senders.planPickingTime"}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255122108417",
        code: "s/waybill",
        visible: true,
        width: 130,
        export: true,
        title: "派件要求车型",
        type: 4,
        propKey: "createUserId",
        idx: 8,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}],"queKey":"receivers.privateCarName"}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255197605889",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "计划派件时间",
        type: 4,
        propKey: "quotationId",
        idx: 9,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["timeInterval"]}],"queKey":"receivers.planDeliveryTime"}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255218577410",
        code: "s/waybill",
        visible: true,
        width: 120,
        export: true,
        title: "要求时效(H)",
        type: 1,
        propKey: "transportAging",
        idx: 10,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["numberInterval"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255235354625",
        code: "s/waybill",
        visible: true,
        width: 120,
        export: true,
        title: "业务类型",
        type: 1,
        propKey: "businessTypeName",
        idx: 11,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255256326146",
        code: "s/waybill",
        visible: true,
        width: 210,
        export: true,
        title: "发货地",
        type: 4,
        propKey: "senders.*",
        idx: 12,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}],"queKey":"senders.address"}',
        sort: false,
        userId: "1",
    },
    {
        id: "1567038255273103361",
        code: "s/waybill",
        visible: true,
        width: 130,
        export: true,
        title: "始发站点",
        type: 1,
        propKey: "stationName",
        idx: 13,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255294074881",
        code: "s/waybill",
        visible: true,
        width: 210,
        export: true,
        title: "收货地",
        type: 4,
        propKey: "receivers.*",
        idx: 14,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}],"queKey":"receivers.address"}',
        sort: false,
        userId: "1",
    },
    {
        id: "1567038255323435009",
        code: "s/waybill",
        visible: true,
        width: 130,
        export: true,
        title: "目的站点",
        type: 1,
        propKey: "destStationName",
        idx: 15,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255344406529",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "特殊要求",
        type: 4,
        propKey: "valueAddedService",
        idx: 16,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255361183746",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "数量",
        type: 2,
        propKey: "quantity",
        idx: 17,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["numberInterval"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255373766657",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "体积(m³)",
        type: 2,
        propKey: "volume",
        idx: 18,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["numberInterval"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255390543873",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "客户货物重量(kg)",
        type: 2,
        propKey: "grossWeight",
        idx: 19,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["numberInterval"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255403126786",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "货物称重量(kg)",
        type: 2,
        propKey: "actualWeight",
        idx: 20,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["numberInterval"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255424098305",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "重量(kg)",
        type: 2,
        propKey: "weight",
        idx: 21,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["numberInterval"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255440875521",
        code: "s/waybill",
        visible: true,
        width: 150,
        export: true,
        title: "销售",
        type: 1,
        propKey: "sellerName",
        idx: 22,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255457652738",
        code: "s/waybill",
        visible: true,
        width: 120,
        export: true,
        title: "备注",
        type: 1,
        propKey: "remark",
        idx: 23,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["input"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255470235649",
        code: "s/waybill",
        visible: true,
        width: 120,
        export: true,
        title: "创建人",
        type: 1,
        propKey: "createUserName",
        idx: 24,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["user"]}],"queKey":"createUserId"}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255482818562",
        code: "s/waybill",
        visible: true,
        width: 120,
        export: true,
        title: "创建时间",
        type: 3,
        propKey: "createTime",
        idx: 25,
        config: '{"filter":[{"filterMode":"AND","filterTypes":["timeInterval"]}]}',
        sort: true,
        userId: "1",
    },
    {
        id: "1567038255503790081",
        code: "s/waybill",
        visible: true,
        width: 120,
        export: true,
        title: "",
        type: 1,
        propKey: "*",
        idx: 26,
        sort: true,
        virtualCol: true,
        userId: "1",
    },
];
